@ECHO OFF
ECHO VALIDATING FILES
ECHO.
ECHO.
cd "C:\xampp\htdocs\ihmp"
dir
ECHO.
ECHO.
ECHO PRINTING BRANCH LIST
git.exe branch
ECHO.
ECHO.
ECHO FETCHING NEW UPDATED FILES . . . PLEASE WAIT
git.exe pull
ECHO.
ECHO.
ECHO.
ECHO IF YOU ALREADY SEE THE MESSAGE
ECHO "Please press any key to continue . . ."
ECHO YOU CAN NOW CLOSE THE WINDOW
ECHO OR PRESS ENTER TO CLOSE IT
ECHO 
PAUSE